### ISSUE TITLE
Implementation info for CBOR standardization

### ISSUE THREAD

**Issue by jefft0** [ipfs/go-ipld-cbor#23]
I'm in the CBOR session at the IETF conference. As part of pushing an Internet standard they need info on deployed implementations of CBOR. Can someone help me update their wiki? https://github.com/cbor-wg/CBORbis/wiki/Implementation-matrix

**Comment by diasdavid** [comment]
Hi @jefft0!

We have indeed a full implementation of the CBOR spec at https://github.com/dignifiedquire/borc which we use for https://github.com/ipld/js-ipld-dag-cbor. This implementation is faster than 
https://github.com/hildjj/node-cbor but the two will probably merge soon.

Hope this is helpful :)

**Comment by jefft0** [comment]
They already have node-cbor on their wiki. We could add borc, but we also need to add the go implementation. Any feedback on that?

**Comment by diasdavid** [comment]
@jefft0 we use https://github.com/whyrusleeping/cbor/tree/master/go for go
