### ISSUE TITLE
migrate to new cbor lib

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipld-cbor#29]
We should use https://github.com/polydawn/refmt, it was designed with a lot of our usecases in mind

**Comment by magik6k** [comment]
This lib could be also used for serialization of dagNodes (currently ipld modules are hard-coded with `MarshalJson`)

cc @Stebalien

**Comment by Stebalien** [comment]
Missing pieces:

* [ ] CBOR Tags: https://github.com/polydawn/refmt/issues/7
* [ ] UTF-8 Strings: https://github.com/polydawn/refmt/issues/8
* [ ] Big Numbers?

**Comment by Stebalien** [comment]
Note: some quick benchmarking shows that the current library is slightly faster (especially when decoding). However, that may change when decoding/encoding directly to a datastructure rather than an object.

**Comment by Stebalien** [comment]
Yes but it's getting close. I need to review and merge some CID changes (so we'll always just use `cid.Cid` instead of `*cid.Cid`). Then, we'll need to update the refmt version here and we should be good to go.

**Comment by dignifiedquire** [comment]
That is great news :)

Cheers Friedel

**Comment by Stebalien** [comment]
Done.
