### ISSUE TITLE
Links are unnamed

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/go-ipld-cbor#56]
It seems that all links are discovered and resolved without giving them a name.

This contradicts the "link name should be unique" rule as all links are named `""` (? not sure this is a rule actually, just says that in the protobuf version).

Would seem sensible to use the path in the object as the link name. (so the link name should be the path that resolves it).

**Comment by Stebalien** [comment]
See: https://github.com/ipfs/go-ipld-format/issues/23

This is one of the many reasons @warpfork is working on https://github.com/ipld/go-ipld-prime (which will be renamed later). Basically, the "Link" structure is left over from the protobuf days (when all links had names/sizes).

**Comment by hsanjuan** [comment]
This is a dup of #33 .
