### ISSUE TITLE
Include name in node.Link

### ISSUE THREAD

**Issue by dirkmc** [ipfs/go-ipld-cbor#61]
When creating the set of `node.Link`s, the [name is not included](https://github.com/ipfs/go-ipld-cbor/blob/master/node.go#L294)

There is a test for this issue in interface-js-ipfs-core: https://github.com/ipfs/interface-js-ipfs-core/blob/master/src/object/links.js#L187

**Comment by Stebalien** [comment]
See: https://github.com/ipfs/go-ipld-format/issues/9. These links originally came from the "merkledag".

**Comment by dirkmc** [comment]
Ok thanks @Stebalien, I'll close this issue
