### ISSUE TITLE
round-trip marshal/unmarshal to an object with an interface

### ISSUE THREAD

**Issue by tobowers** [ipfs/go-ipld-cbor#63]
We are doing something which is probably particular to us, but I wanted to check in here and see if there are any ideas.

We are creating a protobuf object (which uses an anyof field) and then trying to round-trip through CBOR... as in create object -> marshal to cbornode -> unmarshal to object.

I made a simple reproduction repo: https://github.com/quorumcontrol/cboroneofpb/blob/master/cbortest/cbortest_test.go

The failure is in a comment below the test.

The trouble is that the Payload field is an interface: https://github.com/quorumcontrol/cboroneofpb/blob/master/pb/oneoftest/oneoftest.pb.go#L105

And go's reflect.Set can't set a map[string]interface{} to that type.

In refmt itself we could probably do something custom for marshaling, but since it's behind cbornode it seems tricky.

Any thoughts?

**Comment by tobowers** [comment]
Looks like it might be possible to do the custom formatter?

https://github.com/ipfs/go-hamt-ipld/blob/master/ipld.go#L29-L39

**Comment by warpfork** [comment]
You're right, the cbornode indirections make this a little tricky to see, but yes indeed, you should be able to use the `RegisterCborType` function with a fancy `AtlasEntry` of your liking: https://github.com/ipfs/go-ipld-cbor/blob/b7e8f2be4f3ecd5a9616cfd311c3165cb55efba3/refmt.go#L65

The "unions" feature might be just the thing you want: https://github.com/polydawn/refmt/pull/30  It works with interfaces, and serializes the type hint as a map key.

**Comment by tobowers** [comment]
Thanks for the info.
